version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres-docker
      POSTGRES_PASSWORD: postgres-pass
      POSTGRES_DB: server-manager

  backend:
    image: server-manager-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/server-manager
      SPRING_DATASOURCE_USERNAME: postgres-docker
      SPRING_DATASOURCE_PASSWORD: postgres-pass
