
spring:
  datasource:
    password: postgres-pass
    url: jdbc:postgresql://postgres:5432/server-manager
    username: postgres-docker
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true